apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    type: web
spec:
  containers:
  - name: container
    image: kubetm/app:v1
  terminationGracePeriodSeconds: 0 # 삭제 시 바로 파드 삭제
  # 기본적으로 파드 생성 후 30초 후에 삭제되도록 설정되어있음