apiVersion: v1
kind: Pod
metadata:
  name: whoami-rp
  labels:
    type: app
spec:
  containers:
  - name: app
    image: subicura/whoami:1
    readinessProbe:
      httpGet: # 해당 path 및 Port의 live 상태 여부에 따라 ready 상태 여부 결정
        path: /not/exist 
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 2 # Defaults 1
      periodSeconds: 5 # Defaults 10
      failureThreshold: 1 # Defaults 3