apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
     app: pod
spec:
  nodeSelector:
    kubernetes.io/hostname: tmax-b460mds3h
  containers:
  - name: container
    image: kubetm/app
    ports:
    - containerPort: 8080