apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-03
spec:
  # capacity, accessMode에 따라 PVC에 자동으로 연결
  capacity:
    storage: 2G
  accessModes:
  - ReadWriteOnce
  local:
    path: /node-v
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [k8s-node1]}
        # PV들은 values에 라벨링 된 노드 위에만 생성
        # 파드가 무조건 지정된 노드위에만 생성 -> 데이터 영속성 존재